### ISSUE TITLE
 Support intermediate certificate authority

### ISSUE THREAD

**Issue by TonyTangAndroid** [commonsguy/cwac-netsecurity#12]
Hello there,

This is an awesome library that makes it so easy to secure the network communication in our application.  But I am running an issue that the Android Application is not trusting **intermediate certificate authority**. And I have searched it over the Internet and come to this section on the [android official document](https://developer.android.com/training/articles/security-ssl.html#MissingCa), which states that 

> 1. Configure the server to include the intermediate CA in the server chain. Most CAs provide documentation on how to do this for all common web servers. This is the only approach if you need the site to work with default Android browsers at least through Android 4.2.
> 2. Or, treat the intermediate CA like any other unknown CA, and create a TrustManager to trust it directly, as done in the previous two sections.

Since for now, we are not able to make the server changes. I am wondering whether it is possible to make the changes from Client side by modifying the TrustManager in this library.

I am not even sure whether I should submit the issue here or at the OkHttp repository. So I will just give a try here. Any help or hint will be greatly appreciated.

Best regards,
Tony

**Comment by commonsguy** [comment]
> This is an awesome library that makes it so easy to secure the network communication in our application.

Um, thanks!

> But I am running an issue that the Android Application is not trusting intermediate certificate authority.

Did you configure its certificate in the network security configuration?

BTW, this is an issue tracker, not a support board. Please use [the multiple support options outlined in the documentation](https://github.com/commonsguy/cwac-netsecurity#questions) in the future.

**Comment by TonyTangAndroid** [comment]
If I add the certificate in net_security_config, it works good.  What I was trying to achieve is to make respect the intermediate certificate authority as long as its root certificate could be trusted. After coordinating with Server Engineer, we resolved this problem from server side per the instruction from [android official document](https://developer.android.com/training/articles/security-ssl.html#MissingCa).

**Comment by commonsguy** [comment]
Glad to hear you got it working!
