### ISSUE TITLE
cert pinning with okHttp doesn't work correctly with self signed cert

### ISSUE THREAD

**Issue by filipkowicz** [commonsguy/cwac-netsecurity#16]
I've found issue with cert pinning with OkHttp using Andorid 6.0, on Android 7.0 it works well.

current setup:
self-signed cert defined in xml:
```
<network-security-config>
    <domain-config>
        <domain includeSubdomains="true">xxxxxxxx.com</domain>
        <pin-set>
            <pin digest="SHA-256">XXXXXXXXXXXXXXXXXXXX</pin>
        </pin-set>
        <trust-anchors>
            <certificates src="@raw/cert_file" />
        </trust-anchors>
    </domain-config>
</network-security-config>
```

using okHttp certpinning feature:
```
OkHttpClient.Builder()
...
.certificatePinner(CertificatePinner.Builder()
            .add(URL, "sha256/XXXXXXXXXXXXXXXXXXXX")
            .build())
```

is failing with:

```javax.net.ssl.SSLPeerUnverifiedException: Failed to find a trusted cert that signed Certificate:```

**Findings:**
because of:
```
@Override
    public X509Certificate[] getAcceptedIssuers() {
        // getAcceptedIssuers is meant to be used to determine which trust anchors the server will
        // accept when verifying clients. Domain specific configs are only for use in checking
        // server trust not client trust so use the default config.
        NetworkSecurityConfig config = mConfig.getConfigForHostname("");
        return config.getTrustManager().getAcceptedIssuers();
    }
``` 
which in fact is used to create OkHttp's CertificateChainCleaner from TrustManager - using `getAcceptedIssuers` under the hood., that is used later to verify server side cert anchors, what finally cause failure on `finding a trusted cert for self-signed cert'

CertificateChainCleaner is used during pin checking in OkHttp

only solution that currently comes to my mind is to make `getAcceptedIssuers()` returning all issuers, including self signed defined in configuration

**Comment by commonsguy** [comment]
You do not appear to be using this library. `CertificatePinner.Builder` is part of OkHttp, not this library. You should not use `CertificatePinner` in conjunction with this library, though it is a fine choice for certificate pinning without this library.

**Comment by filipkowicz** [comment]
I'm using both, and they work well together on android 7 and later. Since you are providing tools to be used with OkHttp it will be nice to add note that it possibly could broke other built in functionality

**Comment by commonsguy** [comment]
> I'm using both, and they work well together on android 7 and later

There is nothing in your question that shows the use of this library, which is why I asked. My guess is that you are using `withManifestConfig()`, so on Android 7.0+ you are using the native implementation rather than the library's own implementation.

> Since you are providing tools to be used with OkHttp it will be nice to add note that it possibly could broke other built in functionality

I have added a paragraph to the README to reflect this. I apologize for the hassle.
