### ISSUE TITLE
add getSocketFactory inside CompositeTrustManager

### ISSUE THREAD

**Issue by xanscale** [commonsguy/cwac-netsecurity#18]
can be useful to have inside `CompositeTrustManager` something like that to integrate this library with `Volley` or others uses:
```
public SSLSocketFactory getSocketFactory() {
    SSLContext ssl = SSLContext.getInstance("TLS");
    ssl.init(null, new X509TrustManager[] { this }, null);
    return ssl.getSocketFactory();
}
```
EDIT: changed suggestion from `TrustManagerBuilder` to `CompositeTrustManager` due to `setHost` method

PS also `applyTo` can be moved from `TrustManagerBuilder` to `CompositeTrustManager`

**Comment by commonsguy** [comment]
I will try to budget time to work on this next week &mdash; thanks for the suggestion!

**Comment by commonsguy** [comment]
@xanscale I uploaded a `0.5.0-SNAPSHOT` version of the core `com.commonsware.cwac:netsecurity` artifact. It adds `getSocketFactory()` and `applyTo()` to `CompositeTrustManager`. Give it a try and let me know if it meets your needs. Thanks!

**Comment by xanscale** [comment]
seams perfect, just a tip: `applyTo` method can use `getSocketFactory`, and `getSocketFactory` can use `buildArray` instead of do same things internally

**Comment by commonsguy** [comment]
OK, I made that change &mdash; thanks! `0.5.0` is available now with these fixes.
