### ISSUE TITLE
Links to security-config page should be updated

### ISSUE THREAD

**Issue by dimsuz** [commonsguy/cwac-netsecurity#6]
Links to `https://developer.android.com/preview/features/security-config.html` which are used in several places in the `README` are not working anymore, I guess google removed that page.

Instead `https://developer.android.com/training/articles/security-config.html` should be used (I guess).
I'll create a PR a bit later if you won't beat me to it (or explicitly state that it is not needed) :)

**Comment by commonsguy** [comment]
I found two occurrences of that URL in the `README` and fixed those, and I don't see any in the advanced docs. Are there others?

Thanks for pointing this out!

**Comment by dimsuz** [comment]
No, I think I also saw only two of them!

**Comment by commonsguy** [comment]
OK, marking as fixed -- thanks again!
